services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    build: ./backend
    container_name: spring-backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/institute_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=yourpassword
      - JWT_SECRET=mySecretKey123456789012345678901234567890AbcDefGhiJklMnoPqrStuVwxYz
      - JWT_EXPIRATION=86400000
      - FRONTEND_URL=http://3.110.29.9
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
