services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    build: ./backend
    container_name: spring-backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: