# Local Development Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/cpv_db
spring.datasource.username=postgres
spring.datasource.password=admin

app.jwtSecret=LocalDevSecretKeyForJWTAuth2026
app.frontend.url=http://localhost:5173

# Local Mail
spring.mail.username=karandevkate001@gmail.com
spring.mail.password=mnwy qisy hvhz lwrt
